"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 120

format = """
[░▒▓█](fg:color_lavender)\
$os\
$username\
(bg:color_lavender fg:color_on_lavender)\
[](bg:color_blue fg:color_lavender)\
$directory\
[](fg:color_blue bg:color_slate)\
$git_branch\
$git_status\
[](fg:color_slate bg:color_navy)\
$nodejs\
$bun\
$rust\
$golang\
$php\
$java\
$kotlin\
$python\
[ ](fg:color_navy)\
\n$character"""

palette = 'tokyo_night'

[palettes.tokyo_night]
color_lavender    = '#a3aed2'
color_on_lavender = '#090c0c'
color_blue        = '#769ff0'
color_on_blue     = '#090c0c'
color_slate       = '#394260'
color_on_slate    = '#769ff0'
color_navy        = '#212736'
color_on_navy     = '#769ff0'

[os]
disabled = false
style = "bg:color_lavender fg:color_on_lavender"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_lavender fg:color_on_lavender"
style_root = "bg:color_lavender fg:color_on_lavender"
format = '[ $user ]($style)'

[directory]
style = "fg:color_on_blue bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_slate"
format = '[[ $symbol $branch ](fg:color_on_slate bg:color_slate)]($style)'

[git_status]
style = "bg:color_slate"
format = '[[($all_status$ahead_behind )](fg:color_on_slate bg:color_slate)]($style)'

[nodejs]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol ($version) ](fg:color_on_navy bg:color_navy)]($style)'

[bun]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol ($version) ](fg:color_on_navy bg:color_navy)]($style)'

[rust]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol ($version) ](fg:color_on_navy bg:color_navy)]($style)'

[golang]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol ($version) ](fg:color_on_navy bg:color_navy)]($style)'

[php]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol ($version) ](fg:color_on_navy bg:color_navy)]($style)'

[java]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol( $version) ](fg:color_on_navy bg:color_navy)]($style)'

[kotlin]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol( $version) ](fg:color_on_navy bg:color_navy)]($style)'

[python]
symbol = ""
style = "bg:color_navy"
format = '[[ $symbol( $version) ](fg:color_on_navy bg:color_navy)]($style)'
